[graph]
all-features = true

[advisories]
yanked = "warn"
ignore = []

[licenses]
confidence-threshold = 0.8
allow = [
    "0BSD",
    "Apache-2.0",
    "BSL-1.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
]
exceptions = []

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
